### PR TITLE
Main script (kinomodel.py)

### PR DESCRIPTION
**Pull request by jiayeguo**
## Description
This script requests information from KLIFS and populates a kinase object.

## Todos
Notable points that this PR has either accomplished or will accomplish.
- need to add functions in the Kinase class to calculate dihedrals and distances
- need to write proper tests for this tool

### CODE REVIEW

**Comment by steven-albanese** [comment]
One suggestion would be to try to make this flexible so that the kinase object can aggregate information about all of the available pdb files for that particular kinase

**Comment by jiayeguo** [comment]
> One suggestion would be to try to make this flexible so that the kinase object can aggregate information about all of the available pdb files for that particular kinase

Thanks Steve!  Actually by querying with one kinase ID you do get all the pdb codes associated with it (each with probably slightly different start and end of the sequence)---but we can definitely gather all these information.

**Comment by steven-albanese** [comment]
Exactly! Maybe `pocket_seq` could take a list of lists?

**Comment by jiayeguo** [comment]
Yes that change should be straight forward.

**Pull request merged**
